apiVersion: v1
kind: Service
metadata:
  name: hola-spring-service
  namespace: dev
spec:
  selector:
    app: hola-spring
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort
